version: '3.7'
services:
  web:
    build: ./web
    expose:
      - '8083'
    depends_on:
      - db
    restart: always
    networks:
      - backend
  db:
    build: ./db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    networks:
      - backend

volumes:
  db:

networks:
  backend: