version: '3.7'
services:
  web:
    build: ./web
    expose:
      - '8083'
    depends_on:
      - db
    environment:
      API_BASE_URL: $API_BASE_URL
      WEBHOOK_URL: $WEBHOOK_URL
      WEBHOOK_AVATAR_URL: $WEBHOOK_AVATAR_URL
    volumes:
      - /home/shared/nginx/www/html/api2.teamfruit.net/images:/images
    restart: always
    networks:
      - backend
      - proxy
  db:
    build: ./db
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    networks:
      - backend

volumes:
  db:

networks:
  backend:
  proxy:
    name: nginx_reverse_proxy